### ISSUE TITLE
help

### ISSUE THREAD

**Issue by mountaincastle47** [davidlinketech/instagram-account-generator#2]
"E:\GITHUB PROGRAMS\instagram-account-generator-main\instagram-account-generator-main\venv\Scripts\python.exe" "E:/GITHUB PROGRAMS/instagram-account-generator-main/instagram-account-generator-main/instagramGen.py"
how many accs to gen?
-->1
[starting thread 0]
Exception in thread Thread-1 (<lambda>):
Traceback (most recent call last):
  File "E:\program\python\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "E:\program\python\Python310\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "E:\GITHUB PROGRAMS\instagram-account-generator-main\instagram-account-generator-main\instagramGen.py", line 414, in <lambda>
    t = threading.Thread(target=lambda h=i:instagen(h, smsapi="YOUR_SMS_API_KEY", country_code="DE", webhook="YOUR_DC_WEBHOOK"))
  File "E:\GITHUB PROGRAMS\instagram-account-generator-main\instagram-account-generator-main\instagramGen.py", line 40, in instagen
    s.proxies = get_session_proxy()
  File "E:\GITHUB PROGRAMS\instagram-account-generator-main\instagram-account-generator-main\instagramGen.py", line 27, in get_session_proxy
    prox_user = proxy.split(':')[2]
IndexError: list index out of range

Process finished with exit code 0

**Comment by davidlinketech** [comment]
I had to fix the filepaths, but this isn't the cause of this error. Please make sure to download the new version with the folder etc. aswell as changing the information in line 414 to your information. Make sure that your proxy-file isn't empty. That should do it.
